sudo: false

env:
  global:
    - R_LIBS_USER=~/R

addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - fabric
      - pandoc
      - r-base-core
      - r-base-dev
      - ed

cache:
  directories:
    - ~/R
    - ~/.linuxbrew

install:
  - R --version
  - R -e 'source("http://bioconductor.org/biocLite.R"); biocLite("BiocInstaller")'
  - R -e '.libPaths(); sessionInfo()'
  - R CMD javareconf -e 'R -e install.packages("rJava",repos="http://cran.at.r-project.org")'
  - Rscript resources/scripts/install_libraries.R

language: clojure
lein: lein2
