env:
  global:
    - R_LIBS_USER=~/R

before_install:
  - echo "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
      | sudo tee /etc/apt/sources.list.d/cran.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/cran.list"
      -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/marutter-c2d4u-precise.list"
      -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  - sudo apt-get install fabric
  - sudo apt-get --purge remove r-base-dev r-base-core r-recommended
  - sudo apt-get install r-base-dev=3.0.3-1precise0 r-cran-xml r-cran-rcurl r-cran-rgl r-recommended=3.0.3-1precise0 r-base-core=3.0.3-1precise0
  - "[ ! -d ${R_LIBS_USER} ] && mkdir ${R_LIBS_USER}"
  - R --version
  - R -e '.libPaths(); sessionInfo()'
  - sudo Rscript resources/scripts/install_libraries.R
  - git clone https://github.com/chapmanb/cloudbiolinux
  - cd cloudbiolinux
  - sudo python setup.py install
  - fab -f fabfile.py -H localhost install_custom:cufflinks
  - cd ..

language: clojure
lein: lein2
script: lein2 midje
