details:
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    trim_reads: read_through
  metadata:
    condition: A
  analysis: RNA-seq
  description: UHRR_rep1
  files:
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950078_1.fastq
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950078_2.fastq
  genome_build: hg19_ERCC
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    trim_reads: read_through
  analysis: RNA-seq
  description: HBRR_rep1
  metadata:
    condition: B
  files:
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950079_1.fastq
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950079_2.fastq
  genome_build: hg19_ERCC
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    trim_reads: read_through
  analysis: RNA-seq
  description: UHRR_rep2
  metadata:
    condition: A
  files:
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950080_1.fastq
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950080_2.fastq
  genome_build: hg19_ERCC
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    trim_reads: read_through
  analysis: RNA-seq
  description: HBRR_rep2
  metadata:
    condition: B
  files:
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950081_1.fastq
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950081_2.fastq
  genome_build: hg19_ERCC
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    trim_reads: read_through
  analysis: RNA-seq
  description: UHRR_rep3
  metadata:
    condition: A
  files:
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950082_1.fastq
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950082_2.fastq
  genome_build: hg19_ERCC
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    trim_reads: read_through
  analysis: RNA-seq
  description: HBRR_rep3
  metadata:
    condition: B
  files:
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950083_1.fastq
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950083_2.fastq
  genome_build: hg19_ERCC
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    trim_reads: read_through
  analysis: RNA-seq
  description: UHRR_rep4
  metadata:
    condition: A
  files:
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950084_1.fastq
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950084_2.fastq
  genome_build: hg19_ERCC
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    trim_reads: read_through
  analysis: RNA-seq
  description: HBRR_rep4
  metadata:
    condition: B
  files:
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950085_1.fastq
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950085_2.fastq
  genome_build: hg19_ERCC
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    trim_reads: read_through
  analysis: RNA-seq
  description: UHRR_rep5
  metadata:
    condition: A
  files:
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950086_1.fastq
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950086_2.fastq
  genome_build: hg19_ERCC
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: tophat2
    quality_format: Standard
    trim_reads: read_through
  analysis: RNA-seq
  description: HBRR_rep5
  metadata:
    condition: B
  files:
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950087_1.fastq
  - /n/hsphS10/hsphfs1/chb/projects/bcbio-rnaseq/data/geo_data/fastq/SRR950087_2.fastq
  genome_build: hg19_ERCC
fc_date: '131111'
fc_name: standardization
upload:
  dir: ../final
